files: api/|blockchain/|mockups/|schemas/|scripts/|tests/
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["-c"]
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ["--check"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--extend-ignore=E203,E501"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
