[tool.isort]
include_trailing_comma = "true"
known_third_party = [
    "PIL",
    "cbor2",
    "Flask",
    "marshmallow",
    "matplotlib",
    "numpy",
    "prometheus_client",
    "psutil",
    "psycopg",
    "psycopg-pool",
    "pylibmc",
    "pytest",
    "toml",
]
line_length = 88
multi_line_output = 3
profile = "black"

[tool.black]
line-length = 88
