{
 "title": "Explorer",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   { "name": "hostname", "query": "witnet.network" }
  ]
 },
 "panels": [
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_nginx_runtime[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_memcached_runtime[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_postgres_runtime[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_synchronization_status_node_1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_synchronization_status_node_2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_synchronization_status_node_3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_synchronization_status_node_4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_node_node_pool_runtime[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blockchain explorer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_blockchain_explorer_runtime[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gunicorn API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_gunicorn_runtime[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Address caching",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "changes(process_caching_addresses_runtime[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU % (user)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % (system)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk (read)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk (write)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"eno1\"}[24h])",
     "legendFormat": "sent"
    },
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"eno1\"}[24h])",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "Network (month)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_network_transmit_bytes_total{device=\"eno1\"}[30d])",
     "legendFormat": "sent"
    },
    {
     "expr": "increase(node_network_receive_bytes_total{device=\"eno1\"}[30d])",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval]))*100",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval]))*100",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes",
     "legendFormat": "used"
    },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eno1\"}[$__rate_interval])",
     "legendFormat": "send"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "API (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=~\"/api/[a-zA-Z0-9_/-]*\"}[24h])) - sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h])) / sum(increase(explorer_http_upstream_time_seconds_count{server_name=\"witnet.network\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"1..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]) or vector(0)))",
     "legendFormat": "1xx"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"2..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]) or vector(0)))",
     "legendFormat": "2xx"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"3..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]) or vector(0)))",
     "legendFormat": "3xx"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"4..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]) or vector(0)))",
     "legendFormat": "4xx"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"5..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]) or vector(0)))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Bytes received (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(explorer_http_request_size_bytes{server_name=\"witnet.network\", status=\"200\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Bytes sent (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(explorer_http_response_size_bytes{server_name=\"witnet.network\", status=\"200\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[24h]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Requests / minute",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/address\"}[24h]) or vector(0)) * 60",
     "legendFormat": "address"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/balances\"}[24h]) or vector(0)) * 60",
     "legendFormat": "balances"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/blockchain\"}[24h]) or vector(0)) * 60",
     "legendFormat": "blockchain"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/epoch\"}[24h]) or vector(0)) * 60",
     "legendFormat": "epoch"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/hash\"}[24h]) or vector(0)) * 60",
     "legendFormat": "hash"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/home\"}[24h]) or vector(0)) * 60",
     "legendFormat": "home"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/mempool\"}[24h]) or vector(0)) * 60",
     "legendFormat": "mempool"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/network\"}[24h]) or vector(0)) * 60",
     "legendFormat": "network"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/priority\"}[24h]) or vector(0)) * 60",
     "legendFormat": "priority"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/reputation\"}[24h]) or vector(0)) * 60",
     "legendFormat": "reputation"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/send\"}[24h]) or vector(0)) * 60",
     "legendFormat": "send"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/status\"}[24h]) or vector(0)) * 60",
     "legendFormat": "status"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/supply_info\"}[24h]) or vector(0)) * 60",
     "legendFormat": "supply info"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/tapi\"}[24h]) or vector(0)) * 60",
     "legendFormat": "tapi"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/utxos\"}[24h]) or vector(0)) * 60",
     "legendFormat": "utxos"
    }
   ]
  },
  {
   "title": "Requests (24h)",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/address\"}[24h]) or vector(0)))",
     "legendFormat": "address"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/balances\"}[24h]) or vector(0)))",
     "legendFormat": "balances"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/blockchain\"}[24h]) or vector(0)))",
     "legendFormat": "blockchain"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/epoch\"}[24h]) or vector(0)))",
     "legendFormat": "epoch"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/hash\"}[24h]) or vector(0)))",
     "legendFormat": "hash"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/home\"}[24h]) or vector(0)))",
     "legendFormat": "home"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/mempool\"}[24h]) or vector(0)))",
     "legendFormat": "mempool"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/network\"}[24h]) or vector(0)))",
     "legendFormat": "network"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/priority\"}[24h]) or vector(0)))",
     "legendFormat": "priority"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/reputation\"}[24h]) or vector(0)))",
     "legendFormat": "reputation"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/send\"}[24h]) or vector(0)))",
     "legendFormat": "send"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/status\"}[24h]) or vector(0)))",
     "legendFormat": "status"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/supply_info\"}[24h]) or vector(0)))",
     "legendFormat": "supply info"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/tapi\"}[24h]) or vector(0)))",
     "legendFormat": "tapi"
    },
    {
     "expr": "round(sum(increase(explorer_http_response_count_total{server_name=\"witnet.network\", uri_path=\"/api/utxos\"}[24h]) or vector(0)))",
     "legendFormat": "utxos"
    }
   ]
  },
  {
   "title": "Response time (24h)",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/address\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/address\"}[24h]) or vector(1))",
     "legendFormat": "address"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/balances\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/balances\"}[24h]) or vector(1))",
     "legendFormat": "balances"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/blockchain\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/blockchain\"}[24h]) or vector(1))",
     "legendFormat": "blockchain"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/epoch\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/epoch\"}[24h]) or vector(1))",
     "legendFormat": "epoch"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/hash\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/hash\"}[24h]) or vector(1))",
     "legendFormat": "hash"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/home\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/home\"}[24h]) or vector(1))",
     "legendFormat": "home"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/mempool\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/mempool\"}[24h]) or vector(1))",
     "legendFormat": "mempool"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/network\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/network\"}[24h]) or vector(1))",
     "legendFormat": "network"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/priority\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/priority\"}[24h]) or vector(1))",
     "legendFormat": "priority"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/reputation\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/reputation\"}[24h]) or vector(1))",
     "legendFormat": "reputation"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/send\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/send\"}[24h]) or vector(1))",
     "legendFormat": "send"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/status\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/status\"}[24h]) or vector(1))",
     "legendFormat": "status"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/supply_info\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/supply_info\"}[24h]) or vector(1))",
     "legendFormat": "supply info"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/tapi\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/tapi\"}[24h]) or vector(1))",
     "legendFormat": "tapi"
    },
    {
     "expr": "sum(increase(explorer_http_upstream_time_seconds_sum{server_name=\"witnet.network\", uri_path=\"/api/utxos\"}[24h]) or vector(0)) / sum(increase(explorer_http_upstream_time_seconds_hist_count{server_name=\"witnet.network\", uri_path=\"/api/utxos\"}[24h]) or vector(1))",
     "legendFormat": "utxos"
    }
   ]
  },
  {
   "title": "Request duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(explorer_http_response_time_seconds_hist_bucket{server_name=\"witnet.network\", status=\"200\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(explorer_http_response_time_seconds_hist_bucket{server_name=\"witnet.network\", status=\"200\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(explorer_http_response_time_seconds_hist_bucket{server_name=\"witnet.network\", status=\"200\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(explorer_http_response_time_seconds_hist_bucket{server_name=\"witnet.network\", status=\"200\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Responses / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"1..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval]) or vector(0)) * 60",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"2..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval]) or vector(0)) * 60",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"3..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval]) or vector(0)) * 60",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"4..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval]) or vector(0)) * 60",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(explorer_http_response_count_total{server_name=\"witnet.network\", status=~\"5..\", uri_path=~\"/api/hash|/api/address|/api/epoch|/api/home|/api/supply_info|/api/reputation|/api/balances|/api/network|/api/mempool|/api/blockchain|/api/utxos|/api/tapi|/api/status|/api/send|/api/priority\"}[$__rate_interval]) or vector(0)) * 60",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Memcached", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memcached_info_uptime", "legendFormat": "Hit rate" }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memcached_info_limit_maxbytes", "legendFormat": "Hit rate" }
   ]
  },
  {
   "title": "Hit rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(memcached_counter_get_hits_total[1h]) / avg_over_time(memcached_counter_cmd_get_total[1h]) * 100",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Storage used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_gauge_bytes / memcached_info_limit_maxbytes * 100",
     "legendFormat": "Storage used"
    }
   ]
  },
  {
   "title": "Get / minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(memcached_counter_cmd_get_total[$__rate_interval]) * 60",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Set / minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(memcached_counter_cmd_set_total[$__rate_interval]) * 60",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Current items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memcached_gauge_curr_items", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Lifetime items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_counter_total_items_total",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Cache contents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "memcached_gauge_curr_items", "legendFormat": "Items" },
    { "expr": "memcached_gauge_bytes", "legendFormat": "Bytes" }
   ]
  },
  {
   "title": "Commands / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(memcached_counter_cmd_get_total[$__rate_interval]) * 60",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(memcached_counter_cmd_set_total[$__rate_interval]) * 60",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Read / Write bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(memcached_counter_bytes_read_total[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(memcached_counter_bytes_written_total[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Expiries / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(memcached_counter_get_expired_total[$__rate_interval]) * 60",
     "legendFormat": "Expiries"
    }
   ]
  },
  {
   "title": "Evictions / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "rate(memcached_counter_evictions_total[$__rate_interval]) * 60",
     "legendFormat": "Expiries"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "memcached_gauge_curr_connections",
     "legendFormat": "Evictions"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table size",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_class_disk_usage_table_bytes{datname=\"explorer\", schemaname=\"public\", relname!~\"[a-z_]*_pkey|idx_[a-z_]*|[a-z_]*_id_seq[0-9]*\"} - pg_class_disk_usage_index_bytes{datname=\"explorer\", schemaname=\"public\", relname!~\"[a-z_]*_pkey|idx_[a-z_]*|[a-z_]*_id_seq[0-9]*\"} > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index size",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_class_disk_usage_table_bytes{datname=\"explorer\", schemaname=\"public\", relname=~\"idx_[a-z_]*|[a-z_]*_pkey\"} > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Table rows",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_class_table_rows{datname=\"explorer\", schemaname=\"public\", relname!~\"[a-z_]*_pkey|idx_[a-z_]*|[a-z_]*_id_seq[0-9]*\"} > 0",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Inserted rows / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=~\"explorer\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Updated rows / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=~\"explorer\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Scanned rows / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=~\"explorer\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Selected rows / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=~\"explorer\"}[$__rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transactions / second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"explorer\"}[5m])",
     "legendFormat": "commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"explorer\"}[5m])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 92 },
   "targets": [
    {
     "expr": "sum(pg_locks_count{datname=\"explorer\", mode=~\"[a-z]*sharelock\"})",
     "legendFormat": "Shared locks"
    },
    {
     "expr": "sum(pg_locks_count{datname=\"explorer\", mode=~\"[a-z]*exclusivelock\"})",
     "legendFormat": "Exclusive locks"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
     "legendFormat": "state: {{state}}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=\"explorer\"}) / (sum(pg_stat_database_blks_hit{datname=\"explorer\"}) + sum(pg_stat_database_blks_read{datname=\"explorer\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}