global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "process_exporter"
    static_configs:
      - targets: ["localhost:9200"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "nginxlog_exporter"
    static_configs:
      - targets: ["localhost:9125"]

  - job_name: "memcached_exporter"
    static_configs:
      - targets: ["localhost:9150"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["localhost:9187"]
