name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cbor flask==2.3.2 flask_smorest==0.42.0 marshmallow Pillow psycopg[pool] pylibmc pytest toml
      - name: Run pytest
        run: |
          python -m pytest
